
export const SAVE_TOKENS_CONSTANT = {
  ACCESS_TOKEN: '@ACCESS_TOKEN',
  REFRESH_TOKEN: '@REFRESH_TOKEN',
};
export const USER_AUTH = '@userauth';

export const typeConstants = {
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  CREATE: 'CREATE',
  GET_ALL: 'GET_ALL',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  GET_ALL_USERS: 'GET_ALL_USERS',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  GET_DASHBOARD: 'GET_DASHBOARD',
  GET_RECOVERY_QUESTIONS:"GET_RECOVERY_QUESTIONS",
  CREATE_RECOVERY_QUESTION:"CREATE_RECOVERY_QUESTION",
  UPDATE_RECOVERY_QUESTION:"UPDATE_RECOVERY_QUESTION",
  DELETE_RECOVERY_QUESTION:"DELETE_RECOVERY_QUESTION", 
  GET_FEED_CARDS: 'GET_FEED_CARDS',
  GET_EVENTS: 'GET_EVENTS',
  GET_EVENT_BY_ID: 'GET_EVENT_BY_ID',
  UPLOAD_EVENT: 'UPLOAD_EVENT',
  GET_NOTIFICATION: 'GET_NOTIFICATION',
  GET_MATCHES: 'GET_MATCHES',
  UPLOAD_FORUM: 'UPLOAD_FORUM',
  ADD_COMMENT: 'ADD_COMMENT',
  LIKE_USER: 'LIKE_USER',
  BAN_USER: 'BAN_USER',
  UNLIKE_USER: 'UNLIKE_USER',
  FORUM_LIKE: 'FORUM_LIKE',
  OTP: 'OTP',
  RESEND_OTP: 'RESEND_OTP',
  UPDATE_EMAIL: 'UPDATE_EMAIL',
  PROFILEUPDATE: 'PROFILEUPDATE',
  PROFILEUPLOAD: 'PROFILEUPLOAD',
  CHECK_AUTH: 'CHECK_AUTH',
  LOGOUT_AUTH: 'LOGOUT_AUTH',
  DELETE_AUTH: 'DELETE_DELETE',
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  GET_ALL_DONOR_ORDER_LISTING: 'GET_ALL_DONOR_ORDER_LISTING',
  GET_ALL_RECIEPIENT_ORDER_LISTING: 'GET_ALL_RECIEPIENT_ORDER_LISTING',
  GET_RECIPIENT_ORDER: 'GET_RECIPIENT_ORDER',
  GET_DONOR_ORDER_REQUEST: 'GET_DONOR_ORDER_REQUEST',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: ' RESET_PASSWORD',
  CREATE_CHILD_PROFILE: 'CREATE_CHILD_PROFILE',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  DONOR_LIST_ORDER: 'DONOR_LIST_ORDER',
  RECIPIENT_ORDER_REQUEST: 'RECIPIENT_ORDER_REQUEST',
  TOGGLE_VISIBILITY_DONOR: 'TOGGLE_VISIBILITY_DONOR',
  DONOR_ACCEPT_OR_REJECT_ORDER: 'DONOR_ACCEPT_OR_REJECT_ORDER',
  UPDATE_BABY_INFO: 'UPDATE_BABY_INFO',
  FORGOT_PASSWORD_OTP: 'FORGOT_PASSWORD_OTP',
  FORGOT_PASSWORD_CREATE: 'FORGOT_PASSWORD_CREATE',
  CREATE_FORGOT_PASSWORD: 'CREATE_FORGOT_PASSWORD',
  RECIPIENT_ORDER_RECEIVED: 'RECIPIENT_ORDER_RECEIVED',
  TOGGLE_ANONYMOUS_MODE: 'TOGGLE_ANONYMOUS_MODE',
  GET_DONOR_PROFILE_STATS: 'GET_DONOR_PROFILE_STATS',
  RECIPIENT_GIVER_REVIEW: 'RECIPIENT_GIVER_REVIEW',
  GET_DONOR_HISTORY: 'GET_DONOR_HISTORY',
};

export const emailRegx =
  /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|.(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

// Screen Types for better organization
export const SCREEN_TYPES = {
  PUBLIC: 'public', // No authentication required
  EMAIL_VERIFICATION: 'email_verification', // Requires signup but email not verified
  PROFILE_SETUP: 'PROFILE_SETUP', // Email verified but business profile incomplete
  PRIVATE: 'private', // All setup complete
};

// Default placeholder image for profile pictures
export const DEFAULT_PROFILE_IMAGE =
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTARHCPrgly9x-1TlRPk2jQhRYZ3SrWEnp-cA&s';
